server:
  port: 8081
spring:
  application:
    name: "solicitudes"

  r2dbc:
    pool:
      enabled: false
  devtools:
    add-properties: false
adapters:
  r2dbc:
    host: "${MYSQL_HOST:localhost}"
    port: "${MYSQL_PORT:3307}"
    database: "${MYSQL_DATABASE:solicitudes}"
    username: "${MYSQL_USER:myuser}"
    password: "${MYSQL_PASSWORD:mypassword}"
    ssl-enabled: "${MYSQL_SSL_ENABLED:true}"
routes:
  paths:
    solicitud: "/api/v1/solicitud"

security:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-key-1234567890abcdef}
    expiration: ${JWT_EXPIRATION:3600000}

aws:
  sqs:
    email: ${AWS_SQS_EMAIL:https://sqs.us-east-2.amazonaws.com/925323749763/SolicitudDecididaQueue}
    validacion: ${AWS_SQS_VALIDACION:https://sqs.us-east-2.amazonaws.com/925323749763/PeticionCapacidadDeEndeudamientoQueue}
    respuesta: ${AWS_SQS_RESPUESTA:https://sqs.us-east-2.amazonaws.com/925323749763/respuestaCapacidadEndeudamientoQueue}
    solicitud-aprobada: ${AWS_SQS_SOLICITUD_APROBADA:https://sqs.us-east-2.amazonaws.com/925323749763/SolicitudAprobadaQueue}
external:
  api:
    usuario:
      base-url: "${USUARIO_API_URL:http://localhost:8080}"


  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    db:
      enabled: false
    r2dbc:
      enabled: false
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: Mi API